-- liquibase formatted sql

--changeSet anatoly:1
CREATE TABLE adoptive_parent (
                       id bigint generated by default as identity primary key,
                       chat_id bigint,
                       name text,
                       phone_number bigint,
                       address text,
                       message text,
                       type_dis text
);


